#!/bin/sh
PAGE=$1
ROOT=$2

sed "s,<head>,<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.documentfoundation.org/themes/tdf/css/layout.css?m=1300292397\"/><link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.documentfoundation.org/themes/tdf/css/typography.css?m=1292094211\"/><link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.documentfoundation.org/themes/tdf/css/form.css?m=1305575430\"/><link rel=\"icon\" href=\"http://www.documentfoundation.org/favicon.ico\"/>,i;s,<body>,<body xmlns=\"http://www.w3.org/1999/xhtml\"><div id=\"BgContainer\"><div id=\"Container\"><div id=\"Header\"><h1>The Document Foundation</h1><p>The home of LibreOffice</p></div><div class=\"clear\"><!-- --></div><div id=\"Layout\">,i;s,<\/body>/,//,g" $PAGE

cat <<-FOOT
        <div id="Footer">
          <div class="footerTop">
            <!-- -->
          </div>
          <table>
            <tr>
              <td><a href="/privacy">Privacy Policy</a> | <a href="/imprint">Impressum (Legal Info)</a> | Copyright information: Unless otherwise specified, all text 
     and images on this website are licensed under the <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons 
     Attribution-Share Alike 3.0 License</a>. This site is based on the <a href="http://www.gnome.org/">GNOME Foundation</a> election system, whose textual content is itself available under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons 
              Attribution 3.0 License</a>, and the underlying voting code, which is available under GPLv2+. This does not include the source code of LibreOffice, which is licensed under the GNU Lesser General 
     Public License (<a href="http://www.libreoffice.org/download/license/">LGPLv3</a>).<br/>
     "LibreOffice" and "The Document Foundation" are registered trademarks. Their respective logos and icons are subject to 
     international copyright laws. The use of these therefore is subject to our
     <a href="http://wiki.documentfoundation.org/TradeMark_Policy">trademark policy</a>.
  </td>
            </tr>
          </table>
        </div>
      </div>
    </body>

</html>
FOOT
